# Generated by Django 2.1.4 on 2019-04-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20190425_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='anons',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Краткое содержание'),
        ),
    ]
