# Generated by Django 2.1.4 on 2019-04-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20190425_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='medal',
            field=models.CharField(choices=[('Золотая', 'Золотая'), ('Серебрянная', 'Серебрянная'), ('Бронзовая', 'Бронзовая')], default='Золотая', max_length=100, verbose_name='Вид медали'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_type',
            field=models.CharField(choices=[('Новость', 'Новость'), ('Грядущее событие', 'Грядущее событие')], default='Новость', max_length=50, verbose_name='Вид события'),
        ),
    ]
