# Generated by Django 2.1.4 on 2019-04-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20190425_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Достижение'),
        ),
    ]
