# Generated by Django 2.1.4 on 2019-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_auto_20190425_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='type',
            field=models.CharField(choices=[('Для детей', 'Для детей'), ('Для родителей', 'Для родителей'), ('Другое', 'Другое')], default='Другое', max_length=100, verbose_name='Для кого статья'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='comment',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='materials',
            name='video_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название видео'),
        ),
    ]
