# Generated by Django 2.1.4 on 2019-04-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_auto_20190425_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videogalerry',
            name='video',
            field=models.FileField(blank=True, max_length=256, null=True, upload_to='Main/VideoGallery', verbose_name='Видео'),
        ),
    ]
