# Generated by Django 2.1.4 on 2019-04-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_auto_20190426_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoGalerry',
            new_name='VideoGallery',
        ),
        migrations.AlterModelOptions(
            name='achievements',
            options={'ordering': ['-id'], 'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='materials',
            options={'ordering': ['-id'], 'verbose_name': 'Статья из учебных материалов', 'verbose_name_plural': 'Статьи из учебных материалов'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='sportcard',
            options={'ordering': ['-id'], 'verbose_name': 'Карточка спортсмена', 'verbose_name_plural': 'Карточки спортсменов'},
        ),
        migrations.AlterModelOptions(
            name='trenercard',
            options={'ordering': ['-id'], 'verbose_name': 'Карточка тренера', 'verbose_name_plural': 'Карточки тренеров'},
        ),
        migrations.AlterModelOptions(
            name='videoalbums',
            options={'ordering': ['-id'], 'verbose_name': 'Альбом видое', 'verbose_name_plural': 'Альбомы видео'},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'ordering': ['-id'], 'verbose_name': 'Видеозапись', 'verbose_name_plural': 'Видеозаписи'},
        ),
        migrations.AlterField(
            model_name='materials',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания статьи'),
        ),
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
