# Generated by Django 2.1.4 on 2019-04-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_auto_20190427_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='photo_small',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='Main/PhotoGallery', verbose_name='Фото'),
        ),
    ]
