# Generated by Django 2.1.4 on 2019-04-30 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_photogallery_photo_small'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photogallery',
            name='photo_small',
        ),
    ]
