# Generated by Django 2.1.4 on 2019-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_remove_photogallery_photo_small'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='medal',
            field=models.CharField(choices=[('gold', 'Золотая'), ('silver', 'Серебрянная'), ('bronze', 'Бронзовая')], default='gold', max_length=100, verbose_name='Вид медали'),
        ),
    ]
