# Generated by Django 2.1.4 on 2019-05-04 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0013_auto_20190501_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportcard',
            name='status',
            field=models.CharField(choices=[('unosha', 'Призер юношеских соревнований'), ('student', 'Призер студенческих соревнований'), ('master', 'Мастер спорта')], default='master', max_length=60, verbose_name='Сектор доски почета'),
        ),
    ]
