# Generated by Django 2.1.4 on 2019-05-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0014_sportcard_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='videogallery',
            name='cover',
            field=models.ImageField(blank=True, max_length=256, null=True, upload_to='Main/covers', verbose_name='Превью'),
        ),
    ]
